"""Structured output: machine-readable JSON and a human-readable Markdown report.

``results.json`` is the source of truth (and is what you'd feed into another
tool). ``report.md`` is the engagement-friendly summary.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone

from scopehound import __version__
from scopehound.context import RunContext

JSON_FILENAME = "results.json"
MARKDOWN_FILENAME = "report.md"


def _manifest(ctx: RunContext) -> dict:
    return {
        "tool": "scopehound",
        "version": __version__,
        "target": ctx.target,
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "phases": [p.to_dict() for p in ctx.phase_results],
        "summary": {
            "subdomains": len(ctx.subdomains),
            "hosts": len(ctx.hosts),
            "open_ports": sum(len(h.ports) for h in ctx.hosts),
            "http_services": len(ctx.http_services),
            "screenshots": sum(1 for s in ctx.http_services if s.screenshot),
        },
    }


def to_dict(ctx: RunContext) -> dict:
    """Serialise the full run state to a JSON-ready dict."""

    return {
        "manifest": _manifest(ctx),
        "subdomains": [s.to_dict() for s in sorted(ctx.subdomains, key=lambda x: x.host)],
        "hosts": [h.to_dict() for h in sorted(ctx.hosts, key=lambda x: x.ip)],
        "http_services": [s.to_dict() for s in sorted(ctx.http_services, key=lambda x: x.url)],
    }


def write_json(ctx: RunContext) -> str:
    path = ctx.output_dir / JSON_FILENAME
    path.write_text(json.dumps(to_dict(ctx), indent=2), encoding="utf-8")
    return str(path)


def write_markdown(ctx: RunContext) -> str:
    data = to_dict(ctx)
    summary = data["manifest"]["summary"]
    lines: list[str] = []
    a = lines.append

    a(f"# Recon report - {ctx.target}")
    a("")
    a(f"_Generated by scopehound v{__version__} at {data['manifest']['generated_at']}_")
    a("")

    a("## Summary")
    a("")
    a("| Metric | Count |")
    a("| --- | --- |")
    a(f"| Subdomains (in scope) | {summary['subdomains']} |")
    a(f"| Hosts | {summary['hosts']} |")
    a(f"| Open ports | {summary['open_ports']} |")
    a(f"| Live HTTP services | {summary['http_services']} |")
    a(f"| Screenshots | {summary['screenshots']} |")
    a("")

    a("## Phases")
    a("")
    a("| Phase | Status | Detail |")
    a("| --- | --- | --- |")
    for phase in data["manifest"]["phases"]:
        a(f"| {phase['name']} | {phase['status']} | {phase['detail']} |")
    a("")

    if data["subdomains"]:
        a("## Subdomains")
        a("")
        for sub in data["subdomains"]:
            sources = ", ".join(sub["sources"])
            ips = ", ".join(sub["resolved_ips"]) or "-"
            a(f"- `{sub['host']}` (sources: {sources}; ips: {ips})")
        a("")

    if data["hosts"]:
        a("## Hosts & open ports")
        a("")
        for host in data["hosts"]:
            names = ", ".join(host["hostnames"]) or "-"
            a(f"### {host['ip']}")
            a("")
            a(f"Hostnames: {names}")
            a("")
            if host["ports"]:
                a("| Port | Service | Product | Version |")
                a("| --- | --- | --- | --- |")
                for port in host["ports"]:
                    a(
                        f"| {port['number']}/{port['protocol']} | {port['service'] or '-'} "
                        f"| {port['product'] or '-'} | {port['version'] or '-'} |"
                    )
            else:
                a("_No open ports._")
            a("")

    if data["http_services"]:
        a("## Live HTTP services")
        a("")
        for svc in data["http_services"]:
            a(f"### {svc['url']}")
            a("")
            a(f"- Status: {svc['status_code']}")
            a(f"- Title: {svc['title'] or '-'}")
            a(f"- Server: {svc['webserver'] or '-'}")
            techs = ", ".join(svc["technologies"]) or "-"
            a(f"- Technologies: {techs}")
            if svc["screenshot"]:
                a(f"- Screenshot: ![{svc['url']}]({svc['screenshot']})")
            a("")

    path = ctx.output_dir / MARKDOWN_FILENAME
    path.write_text("\n".join(lines), encoding="utf-8")
    return str(path)


def write_all(ctx: RunContext) -> tuple[str, str]:
    return write_json(ctx), write_markdown(ctx)
